# Generated by Django 4.2.4 on 2023-08-08 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="amount",
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="credit",
            name="date",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="credit",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="amount",
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="sell",
            name="date",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="sell",
            name="phone_number",
            field=models.CharField(
                editable=False,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+989133333333' or '09133333333'.",
                        regex="^((\\+98)|0)\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="seller",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
