# Generated by Django 4.2.4 on 2023-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_profile_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="credit",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=13),
        ),
    ]
