# Generated by Django 4.2.4 on 2023-08-16 07:12

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_profile_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="amount",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name="profile",
            name="credit",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=13,
                validators=[web.models.validate_non_negative],
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="amount",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=13),
        ),
    ]
