# Generated by Django 4.2.4 on 2023-08-16 11:23

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_alter_sell_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="amount",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=13,
                validators=[web.models.validate_positive],
            ),
        ),
    ]
